package com.teamyostrik.easystock.exceptions;

public enum ErrorCode {

    ARTICLE_NOT_FOUND(1000),
    ARTICLE_NOT_VALID(1001),
    ARTICLE_ALRAEDY_IN_USE(1003),

    CATEGORY_NOT_FOUND(2000),
    CATEGORY_NOT_VALID(2001),
    CATEGORY_ALRAEDY_IN_USE(2003),

    CLIENT_NOT_FOUND(3000),
    CLIENT_NOT_VALID(3001),
    CLIENT_ALRAEDY_IN_USE(3003),

    COMMANDE_CLIENT_NOT_FOUND(4000),
    COMMANDE_CLIENT_NOT_VALID(4001),
    COMMANDE_CLIENT_NOT_MODIFIABLE(4003),
    COMMANDE_CLIENT_ALRAEDY_IN_USE(4004),

    COMMANDE_FOURNISSEUR_NOT_FOUND(5000),
    COMMANDE_FOURNISSEUR_NOT_VALID(5001),
    COMMANDE_FOURNISSEUR_NOT_MODIFIABLE(5003),
    COMMANDE_FOURNISSEUR_ALRAEDY_IN_USE(5004),

    ENTREPRISE_NOT_FOUND(6000),
    ENTREPRISE_NOT_VALID(6001),

    FOURNISSEUR_NOT_FOUND(7000),
    FOURNISSEUR_NOT_VALID(7001),
    FOURNISSEUR_ALRAEDY_IN_USE(3003),

    LIGNE_COMMANDE_CLIENT_NOT_FOUND(8000),
    LIGNE_COMMANDE_CLIENT_NOT_VALID(8001),

    LIGNE_COMMANDE_FOURNISSEUR_NOT_FOUND(9000),
    LIGNE_COMMANDE_FOURNISSEUR_NOT_VALID(9001),

    MOUVEMENT_STOCK_NOT_FOUND(10000),
    MOUVEMENT_STOCK_NOT_VALID(1001),
    UTILISATEUR_NOT_FOUND(11000),
    UTILISATEUR_NOT_VALID(11001),
    UTILISATEUR_ALRAEDY_EXIST(11002),
    UTILISATEUR_CHANGE_PASSWORD_OBJECT_NOT_FOUND(11003),
    VENTE_NOT_FOUND(12000),
    VENTE_NOT_VALID(12001),
    VENTE_ALRAEDY_IN_USE(12003),
    BAD_CREDENTIALS(360),
    UPDATE_PHOTO_EXCEPTION(5400),
    BAD_CONTEXT(450);

    private int code;

    ErrorCode(int code)
    {
        this.code = code;
    }

    public int getCode()
    {
        return code;
    }
}
